<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>0ba39762-65bf-44ef-b367-a66e31f9d1b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[23]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-transparent.show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e53e808-14bf-47ce-90a3-c2d6ce5b54c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52b38690-f6a9-4e9a-9980-dffa6c855fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>09eb6b85-c655-41d6-960c-24b5d242ffd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>038e3597-68f1-4b27-8615-4069e9787ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4f6075b5-f7c9-4288-a0e0-2311f491612f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>d0d9d772-136a-46dd-a0ed-8585f87c94d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>30e4ecea-6f1c-4afe-836d-14d506a86466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5cd5ad2-4b96-4cc8-84b4-daf59e2f0f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>716b1fc2-adb4-44eb-ab08-b77d272cc90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>2cebeb4b-70df-475b-b8c8-b7ac80338053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>d0eb8b3f-665f-40d8-b81e-ca9bd7210b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba3b429c-677d-4ea4-b473-317684ac2ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>ad57289d-77d4-4330-ab21-613dd9098818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>ac295e5a-9bf3-4e40-ab9f-438ceede62e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a73bce4-9f21-4a40-9288-321a255d20e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9660e4ad-6f53-4257-9121-2a925b1591a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>b936f258-1631-40d3-b11d-75a6930c0ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>7c77963f-6658-4bbf-9a52-c759f4a2bf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc2fa010-8d86-4764-bebf-395ce55c0a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>6f969c02-6709-4093-a57c-5d29b61685d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>53ba5cb8-3931-441d-87d4-37cda3084a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3623de4-66f6-4938-b023-766200855375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0acc977b-dcf2-449e-9063-037a0d51b27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>036a5e81-61aa-4071-beca-20e945db43c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>42ec71cb-091c-4a4b-89bb-8cfc918a0b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72f7741e-de10-46c3-bd55-5bba1e1e21d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>3d50e10c-eb29-409a-86b2-4531e5d4fc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>fe0b82bb-4b5f-480a-9f41-98244725affd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e9f1d60-5312-4cfa-975f-3ab5e04a1985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3279b822-7aae-4fc7-90a6-8765ac71ac93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>6c8013a9-aea2-4f2d-bec3-1563a528a8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>9eeb0ec6-5974-4f73-9f6a-2614f94d067c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82b5b413-d971-4cf1-9083-16714b766348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>cfe0a2e9-1e3e-41f8-a48f-d8aa9d6a06a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>463a86e7-175e-4c41-94d7-2bebff9a94ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>099524f8-3e2c-4dee-9233-3a10f63a2275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>609734cb-81ec-49c8-8d05-d7b105a8849f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>18e8ec61-89c2-42a2-a73c-ac93cc94e0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>bce27f74-3d04-43e6-a497-d2e2029fbc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf0c0b98-6753-4bf1-add8-465d30faa72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>9dac5666-77ef-4819-b8a2-af0fd59847cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>e0f2ddc3-7504-4b3a-aa0d-58daa679b3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33a04fba-b346-4128-a063-f9e3a4dbe1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0ce5ece-e33c-471b-a70a-aa933f5399e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>de0bff53-76cf-46c9-aa1e-8fe165441ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>b6a39617-21ca-4987-a5a3-cbe81bf43a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aabe7b4e-e87d-4db4-82cb-d1e6d905697e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>effc3db1-3603-46c4-a1d7-837001593d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>0627169f-76b3-4134-8beb-b720ce75b0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1f10b2c-9840-4635-850e-a1e8d41dcf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dea1b15b-6221-4276-9cbf-9e0cd88d0227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent show</value>
      <webElementGuid>514141b5-f4d9-466f-97ef-87a2262aaadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0ffe2937-674a-407d-a1ae-ff6adee5c4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cfa469e6-ce5b-4344-9fba-80789c2a450e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>•••</value>
      <webElementGuid>ceb7b48a-9c18-4b9b-b26e-218ba1ab4214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-transparent show&quot;]</value>
      <webElementGuid>521cf7d9-7d3d-4898-ba29-8288a8c43438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[23]</value>
      <webElementGuid>f6c489b7-c74c-48a6-9d05-bbc8b28dd1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/table/div[2]/div[6]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>39b50200-0549-4d13-b89d-fb4dd2d9ad30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki - Laki'])[3]/following::button[1]</value>
      <webElementGuid>251233cb-62e1-4401-ab23-99ec086296e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joni'])[1]/following::button[1]</value>
      <webElementGuid>1333dff1-9f0d-4a52-acee-723e871b624a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Data'])[6]/preceding::button[1]</value>
      <webElementGuid>2fa4b85b-d577-49ae-a82a-3df86e69ba75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[6]/preceding::button[2]</value>
      <webElementGuid>19155ea7-f983-4487-8e45-649b1d2bfc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>5989ad84-94a7-464e-be9c-a7db45314494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '•••' or . = '•••')]</value>
      <webElementGuid>7504e3f1-335e-4fd7-a217-b7fdcd795ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[15]</value>
      <webElementGuid>8de99f1d-0896-4cff-93db-5713f8e28621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/table/div[2]/div[4]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>93ab03be-3e0e-40e9-818d-40d8318abbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki - Laki'])[4]/following::button[1]</value>
      <webElementGuid>4665c9ce-0072-4012-bed1-67e8601013df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gunado Siregar 2'])[1]/following::button[1]</value>
      <webElementGuid>e2efa2bf-46fd-4b78-a023-5e746f671e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Data'])[4]/preceding::button[1]</value>
      <webElementGuid>f983dac6-0630-4ad6-946d-a2d9728070b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[4]/preceding::button[2]</value>
      <webElementGuid>aea73d43-56f1-461a-9b53-c03b599868c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>f33690e8-acdc-4e9c-b494-8e9127ce5040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>2ca21229-5f13-497b-9a45-5976d4d8bd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/table/div[2]/div[5]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>b76a07b9-ef82-4e6d-8ab7-bb15334ce4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki - Laki'])[5]/following::button[1]</value>
      <webElementGuid>842190fc-f336-489c-a809-478bdb0c0913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gunado Siregar 3'])[1]/following::button[1]</value>
      <webElementGuid>5477e6bb-d1f3-47a7-9008-dc27d45b6723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Data'])[5]/preceding::button[1]</value>
      <webElementGuid>d039d187-b893-4460-9a48-c978bdb35802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[5]/preceding::button[2]</value>
      <webElementGuid>178afdf0-a1de-43d7-b8d6-bc8cfc2452e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>1865b5fd-acac-4215-8892-d198d19c9055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>ebc9d606-8aae-4700-85be-fb30c079bfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/table/div[2]/div[2]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>ac70c569-72b0-436b-8087-c83670010582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki - Laki'])[2]/following::button[1]</value>
      <webElementGuid>308c8d64-0456-4dbe-9f38-6763363f6e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gunado Siregar'])[1]/following::button[1]</value>
      <webElementGuid>59659ac6-c29b-4e09-9eb4-4ff67fa7ddb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Data'])[2]/preceding::button[1]</value>
      <webElementGuid>b5c754af-36d7-477a-90bc-421a6cf0eadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[2]/preceding::button[2]</value>
      <webElementGuid>4c27e73d-345e-4305-8d36-863af9b696d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/tbody/tr/td[7]/div/button</value>
      <webElementGuid>37f95e4c-07b8-45b2-b8d5-81d977973942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>456d1743-3402-4fbc-9bb8-c6ef9c36af7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/table/div[2]/div/tbody/tr/td[7]/div/button</value>
      <webElementGuid>104bea69-1856-4ffc-b82e-73697e6bfe96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki - Laki'])[1]/following::button[1]</value>
      <webElementGuid>04e53371-081f-4c86-b183-ea7018d5be7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adityo Rahman'])[1]/following::button[1]</value>
      <webElementGuid>fdfa023c-cc97-4932-a261-668d4a3a4ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Data'])[1]/preceding::button[1]</value>
      <webElementGuid>70f65899-add5-4c29-b267-49bb377f3b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[1]/preceding::button[2]</value>
      <webElementGuid>449ddeac-52a0-4e26-b674-5d54c2c4ba13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='•••']/parent::*</value>
      <webElementGuid>23627b1f-0cd4-4d43-ab39-6b0af92e1763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/button</value>
      <webElementGuid>ddfb35bb-fbef-4a73-9d24-00fac0f41ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
