<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Patient</name>
   <tag></tag>
   <elementGuidId>e75434cf-2022-440d-ac0f-ff392a3d57ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/span/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-toggle.d-inline-flex.border-0.poppins-font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bf6e2ed-c98b-41db-a5ec-df59a8069aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>c9d3ee10-1f80-4bf0-b016-e28d47e0bb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>19ab78c3-76c8-4de1-a8f2-efc8b35f9374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>69c87891-d4dc-49de-83db-c79b1a34ef91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e461291d-6bf1-4055-8a25-f0f859feae03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>903c843a-ab29-4749-b6ef-ec6f03e434eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>7225f2c1-cb53-4ce6-81a0-cfd8b434b83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27e0c410-dd57-40a3-b9d6-f2e30469ce10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>b6996824-52b1-493a-8d29-fd88fe4b6150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>d9ea7fbc-8ed2-4ec5-acb7-d4f4b09e3611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>502fa2ff-88cb-4d36-b28c-59f92156b6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d24e91bb-15d4-404b-a441-b83cd2850c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>28d4978e-90a6-45c9-96e7-6713fac795bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>7c63f1d0-9ed6-4821-8c34-48ee560082d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54791783-5be7-4285-a12f-bd4fd33341ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>e906ab3f-658b-4260-b906-8961dad59e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>13db94c6-2273-4258-9778-fc7d25265e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>790dd38d-d263-4601-9479-9ec600fa399a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7d78476-b6c4-41c8-9f91-3f07d25baaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>174234ce-fc6a-47e8-b62c-62b3d78df053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>e78314d9-16cf-4249-92cd-df76f8b0b886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc112598-faba-4d3d-a93d-e40f4d8af9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>3398de3b-5f0c-42f5-93df-6db9d1454b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>2e72207e-e356-4491-8235-366607c47772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>5102df58-abc5-4503-b08d-f62b44c2916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68b0201a-df91-4597-933f-03ce335abfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>6c9da1b5-4a48-4c88-b7ab-0f9a7471aeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>3ea846d3-c0e7-4225-ac4e-913c98f11a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e28a432d-a019-4212-9101-86f237bf26ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>fe154785-cb9d-482b-ba93-df831ecfb047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>d06717db-cab5-48c5-84d1-f0e2f25f5bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>e736a9d8-2452-4656-8779-fbb1e9f595d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f38aebd-0afc-4528-b407-8970abd90d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>d6cdfdd8-99d4-45a8-88bb-9d86d9056d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>3d70fed6-b669-4532-9738-66d43b1306cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11fbc43c-f070-473a-8786-587750477116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>8548d68e-6984-4cd8-9ea4-0c8747abfeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>8b822784-31c6-407b-a03e-c1f1f0d79e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>d5fc0c55-cc5b-4e88-8a1e-c190b845a381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7dab1201-f4b8-49a9-b7f6-b61c12f439de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>f282f244-16bf-430e-a65c-89679045c7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>cb5d7218-6f63-4eee-9896-800f3746f626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8170c1d5-7337-4d3b-a02b-fc20ab73895b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>3a31b8f9-63c2-407f-b36e-acc4056f282b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>cfa91533-9735-40d8-a2af-6b03d502c82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>613a0f9a-ff7c-4a5d-b598-a0c286bb0f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fe9e186-960d-488e-bb5a-432cecbfa706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>2fda2d86-cefa-4f70-afc6-c09dadc90bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>85cc09f6-c601-461d-a04a-86f85fcbb516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>012690fb-39fd-406c-a7a6-c5253cdf2c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>384882fb-2d47-41d6-bbd1-fbaa87ff28f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>7be11b71-f2b0-4b43-8e9e-eac0311f628a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>ed807da0-e56b-4d2c-b8a3-e0f45530432d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b57791d0-1bd7-4ca8-8ee6-4c186ebe5300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>c092a7db-76ae-4fc6-9768-b1c3315282c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>ac23ad51-9996-4f54-8c79-7cee1c2b72e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d918b48e-62f9-46a7-b2df-15319a35f93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>54c2f9c7-08de-4e7e-94d6-ab6cc8756a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>fb3b4807-8a1d-49c0-ba7f-09b44f780da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>ee474bc7-ccce-4d62-85bb-02b8f310032d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8063b3de-69dc-4d64-bcd5-dcd319f436b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>7801f506-8d11-422f-8b40-041014be02be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>08777342-6252-4c0c-bac7-dcb1d83bf3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93f788ef-d1b9-458d-ac84-be920b6841cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>70a0f7c5-ecb5-4ba8-ac04-a710522ad1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>a28d5225-e558-4c6e-ae7d-95c1d38d7039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>31fd7342-398a-4423-b960-04cafc15862f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a7ac801-a273-4df1-a20b-94bdb9b83260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>953bd2b2-2ccc-4e68-be26-03b81810d944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>fbb23542-cae6-4e56-bffc-20ddd1b1a440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66426657-4f30-421c-b519-c91fb0c206d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-toggle d-inline-flex border-0 poppins-font</value>
      <webElementGuid>7c5dc5cb-6021-4c4e-aa3d-5c41fb2f3a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>6e7ff4c3-a7af-44fe-b2e8-3e663121df7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#home-collapse</value>
      <webElementGuid>78d5833e-589e-4b73-905e-8192fa4340ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06668344-c22a-48fd-b988-53ee224ae094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>ac8bed77-1e03-4f60-b683-d34df4b77fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]</value>
      <webElementGuid>155f4901-c57f-4327-a54c-b64adf2e4ccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/span/div/div/button</value>
      <webElementGuid>c25cf0fa-114a-4242-9e78-9eb714533378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::button[1]</value>
      <webElementGuid>99c6842c-249b-40a5-8a8f-70b15a93d299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinic'])[2]/following::button[2]</value>
      <webElementGuid>5776a420-d40e-4577-b197-800aab305e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctors'])[1]/preceding::button[1]</value>
      <webElementGuid>5d2a7158-0f75-4f26-8aed-7a94ecb26bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>4bb04911-9567-4e95-8def-44f37a6b92d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Patient' or . = 'Patient')]</value>
      <webElementGuid>24755628-1e11-4ebc-b1b5-e6817d08981f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
