<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>d97be356-50c6-4e0c-81ea-61f93cde51a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/form/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._btn_1bqjf_62</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>949566e0-9c33-4c29-af0f-cd82ebc89114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>793f7500-653b-45d4-a766-8fa03146556d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a7253353-f4e4-4e7f-b8e2-b5736d4b13f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>228d7b3c-6787-4505-b660-36009e192a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d922c0e-8490-40d9-ae52-e946b351306c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>57e5adbd-10ed-4d50-aa21-be361d851570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>931aef4a-00a4-48d1-abb0-10af04eb669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>b9c23654-ce1e-4f10-8a3b-7a3b2099ee36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83a9c7e4-4f02-4d48-ad68-2568eef658e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>e0823a09-c169-4849-a46d-082abaaae749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>8a997c46-2f96-4341-abf5-6492ba277c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>88db86e9-46cb-4f97-9dca-cc38df8838b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6478491-5ed8-4112-b527-2edde7090c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>e10bf258-4101-4bb6-8e1c-217fc79a1c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>ac586d3f-a1c3-4a5d-8bd1-7bb39ee55a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>b8e0d49e-ddde-48c5-811f-86a606a980dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>890f0950-35ef-4c86-bd04-a331821b03ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>a4083231-4677-44ee-9b2a-faa54875ba19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a700d111-8972-408d-b68e-b165fe2539c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>86cb0c1d-956b-477c-83b6-9789c01906a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>274d018c-811d-4efb-851d-cb4d289e7931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>f2fd4323-8deb-4a79-84f3-9bae30132ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>54479a0c-fe10-4f9e-9a54-6b971f908377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>57f42036-acfc-4214-b056-32faab260017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f38eb60d-f380-4b88-8242-cf5b3272327e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>d962067b-7155-4cf1-abc1-c537f8eade2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>9ac3e333-72b9-4f99-9ba3-e5655308398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>a0d920e7-1876-42c4-a7ba-a1b483dd3a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67e38757-7a58-4830-bd28-af9a4a9fee99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>ca0acfd5-9eb6-416c-8e5c-2e5d7982f0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>b7c8e348-a171-43d4-b1ce-bd419f6dd47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>31933742-41c0-47e8-9dd8-b29f76dd5a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a564e9c5-4429-40f9-94bc-1c243e792f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>2fc28486-c113-432d-a401-4cb4d5f8e5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e95c4e96-8cbd-461b-a359-93eb3a2492de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>2c73b6e0-273c-4e1b-9961-35539a78b2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>106a4155-6bcb-4a9f-9e1c-d4aa59a15377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>54ad1611-6e1e-4480-a9cf-3796165fecb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3657af84-6962-49ec-98df-3f379831badc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>6b099a27-cd22-47a5-a284-56c7faca8455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38840305-4a5a-4399-a10a-682ff705496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>4d21aea4-218c-4832-808f-410122327801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>29c27a94-9bba-492b-af75-94e0f7b7b758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>3978bec5-1e67-4d43-8869-2d9a53756a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1739c61e-f2d5-4f21-a10f-c936bc6b32ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>9a842000-9afa-4220-9d36-b1ac323dc922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4749f523-c6e1-48ba-86e3-9445cfb1e609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>8e216798-cf60-4ca0-a681-473a6b10a2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f109c4e2-9259-4bf1-8968-a53815ded57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>abf5ac27-2cd4-43a3-9531-84a3e1533cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4eee331f-cb46-4dce-bcd7-1c3d4768fecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>dfa59c62-4ac6-48ee-bbb0-9fce98470a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2765bcf4-8c52-4738-bdcc-060f5a48f71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>382dffc7-6a0d-4372-88d1-59fe9628a3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e6dc021c-9cb4-4025-b443-a0721c5011f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>dfcb1b8c-4a25-4793-86a0-6eab5fc5afeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35e7fcda-733b-4ca8-8850-545b0a4d6f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>901a054a-3e4b-4d08-bc0b-dd4da605b2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a7ff17b0-ef23-4dca-ade6-d3fdd0ab3bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>fd85e1f4-c994-4e74-adbd-2b74f7e4c980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fd95222-a7c7-4410-97d5-b3582bb02e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>f78e8c21-0902-4b53-8302-458f7625871c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>2b6a0fc2-5ae5-4c45-b145-2f5d5abf724d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>71bdbd62-9e7f-41d4-a00a-cfda620017e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb0aab69-658a-43fb-a3a8-aa2481c97a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>fa6cd93d-1c2e-486d-8342-f40671c608a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>8f210697-7db5-42c3-b5f3-713bf82b4de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>dc354b3d-9857-4be1-886f-193fa89c5428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36d49a56-b862-4b6f-a654-0a6c8ca13872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>97b315e3-3f00-4c3f-a115-ebd3f13b4ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>240cb43b-e450-4437-be8d-01bb1fc041ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>a0290b4e-bde6-4140-94a8-09d1029d3bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>343c0f8a-39b5-4276-8b94-933af9b6068d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>bf939704-c494-4870-b6cd-7aa14cd35bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>1a15c411-264b-44f3-b6b1-a26826825f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>f64a1011-9916-4763-97a2-7e969072fa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2eadca26-5e3b-409c-8b7c-8fa989190dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>8d5915e1-eb3a-4a5d-b4ad-c0d88d243009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>6bebd1bb-6591-4f1b-a88e-fc1ba9caaeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>0be45522-03cb-4c32-ba5b-399eea10ca48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>552cb77e-6902-478b-aa15-0b7754a609f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>49ddee0c-58fa-451e-a91a-3558e9b68876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>52030ea7-0371-4507-a59f-b98a5427bc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>7f1889fe-8e4e-4696-a981-bbaa4948eb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3340847b-1b33-4f32-96de-0beb72418403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>4fd09a31-c9b3-4201-9e52-6b2501f1650b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>04d897db-9484-471b-8cb8-50dd4d7ecedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>0f7d6ca6-397d-41ea-8bc6-9e348061e69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2bad090f-fefe-446e-9636-a6a135aaa199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>bd142cbe-c10b-4dbe-933b-eca7f719014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>de1adb97-1b0e-4b68-90d9-40e4f5a163be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>8f097c08-0ba1-40d9-ae99-c6875599169c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e27af2d-9ebb-4af9-b95c-680fdb87016c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>411ec848-c0ed-4131-896c-0095599f0224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>d857e235-eb68-469a-911d-06f074f3065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>3a730431-8080-4759-aabd-6d2580cd3b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6dbdeab4-51e3-4651-80c6-1b992015c12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>9a9bb5f8-4f45-44d0-ab1b-23992e48de55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>95020804-86d3-485d-9bf4-ae67aba5f1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>926a50be-2194-4aaa-98c2-45d5cb714e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55505635-85a4-4685-a6e3-1e2add344f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>c0234f2a-7e4c-419c-a056-1abb2f157410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>30bc44c0-ab67-4f52-b3e8-2984434a1c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>d2595c33-5a70-4eff-a9f6-4c8a3afcf0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4e8cb9e-ef18-4470-95f5-085adbc20fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_btn_1bqjf_62</value>
      <webElementGuid>2ebf25df-711c-4645-8703-ae0ee16182bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>67ae7d4c-7a47-4632-9b46-d38ebc6f702d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]/div[@class=&quot;_box_1bqjf_14 _login_1bqjf_26&quot;]/form[1]/button[@class=&quot;_btn_1bqjf_62&quot;]</value>
      <webElementGuid>b49ae505-22cc-4216-8734-74af28942955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/button</value>
      <webElementGuid>c43f8f8a-533f-4635-85fb-913788e16523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang di Cleanic'])[1]/following::button[1]</value>
      <webElementGuid>a250313f-9cc3-4460-ae6b-f9c4172329a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>0a040625-306d-48b2-9337-a0df9fab7ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4b5f17f7-d4f7-47bf-9170-43bdd7304b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>9256ae8a-98f9-4253-96ae-1fc6325d3299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
