<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Selamat Datang di CleanicUsername atau _dc0c4f</name>
   <tag></tag>
   <elementGuidId>59e344a4-4439-441a-8cb0-8dd03b404c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._background_1bqjf_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b375a9a-456f-47ea-bd79-a185f0a58ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_background_1bqjf_3</value>
      <webElementGuid>732a1d9d-c7d2-404e-b913-978fe74fb480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selamat Datang di CleanicUsername atau password yang dimasukkan salah. Mohon periksa kembali.Login</value>
      <webElementGuid>659329f3-7880-4e0c-8771-075b3e0d02ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_background_1bqjf_3&quot;]</value>
      <webElementGuid>efb97e51-40d8-4080-becd-cf0da8a0068a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>8449e4e4-7060-4031-be7f-7099e762fe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>ad41fb0e-78cf-4514-8d23-09fb23a260e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selamat Datang di CleanicUsername atau password yang dimasukkan salah. Mohon periksa kembali.Login' or . = 'Selamat Datang di CleanicUsername atau password yang dimasukkan salah. Mohon periksa kembali.Login')]</value>
      <webElementGuid>4271e635-f7bf-46d2-8663-0c5e696ec161</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
