<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DashboardDoctor jaga hari iniJadwal Tem_20943d</name>
   <tag></tag>
   <elementGuidId>a33ed3cb-6d41-4130-a044-24ec51efd242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-10.col-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a5b2b48-c7f3-43a0-bb67-9784ee073547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-10 col-10</value>
      <webElementGuid>e48e898b-ba86-49ea-bf77-1fb1c01a134e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DashboardDoctor jaga hari iniJadwal Temu PasienNoNamaUsiaKeluhanJadwal TemuTotal DoctorsTotal NursesTotal Patients</value>
      <webElementGuid>9f3b0f9f-bd2a-45c9-b933-03e454a23e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]</value>
      <webElementGuid>a9a75dbe-4d0c-49f1-9979-186ca0ed7056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]</value>
      <webElementGuid>efc312af-fcfd-4024-85e8-f5c60a0fd181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::div[1]</value>
      <webElementGuid>3603b9ae-4893-43b7-a461-a759207ccb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::div[2]</value>
      <webElementGuid>71d07307-cb40-46d7-892b-ddba128d4776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>c1a702ce-b41d-4b2d-b291-ad6e7411af81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DashboardDoctor jaga hari iniJadwal Temu PasienNoNamaUsiaKeluhanJadwal TemuTotal DoctorsTotal NursesTotal Patients' or . = 'DashboardDoctor jaga hari iniJadwal Temu PasienNoNamaUsiaKeluhanJadwal TemuTotal DoctorsTotal NursesTotal Patients')]</value>
      <webElementGuid>3c3cac5f-2ff3-4e35-b4e4-580a2ded4e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
