<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Registrasi Tenaga MedisNamaNomor Lisens_ad60a7</name>
   <tag></tag>
   <elementGuidId>1da67599-2fd9-4673-bc6b-330211a08040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[28]/following::div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fade.modal.show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9e25c7d-23bd-4c81-ba24-77d54b096880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>29b0d95a-918d-47b1-b005-f003c6eb56e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4ed3179-6052-4aa0-8569-4dc3de1a4ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fade modal show</value>
      <webElementGuid>b18b99a2-f5db-4e30-8533-9e4788ca6efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>61f0d0ad-ef1b-4b32-a956-343477bde4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>contained-modal-title-vcenter</value>
      <webElementGuid>858e1cfa-4a7f-498b-a55c-f0abbbeec007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registrasi Tenaga MedisNamaNomor LisensiEmailPasswordJam MulaiUpload FotoTanggal lahirStatus PerkawinanBelum MenikahMenikahSpesialisUmum 2Spesialis penyakit dalamSpesialis penyakit dalamNo TeleponJam SelesaiJadwalmingguseninselasarabukamisjumatsabtuTambah</value>
      <webElementGuid>b26cc55f-ec9a-414b-b70c-bf72608db045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]</value>
      <webElementGuid>9db9a855-ba25-46a1-af89-2f76942bc21b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[28]/following::div[5]</value>
      <webElementGuid>6cebeefe-9f06-4b7f-bf19-d26cbb4c81ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamis'])[2]/following::div[5]</value>
      <webElementGuid>20dd5cae-23bc-4d6d-a2ba-7645d8cbbdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>edc4c9a5-fb16-450f-b981-ee1dfec2e174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Registrasi Tenaga MedisNamaNomor LisensiEmailPasswordJam MulaiUpload FotoTanggal lahirStatus PerkawinanBelum MenikahMenikahSpesialisUmum 2Spesialis penyakit dalamSpesialis penyakit dalamNo TeleponJam SelesaiJadwalmingguseninselasarabukamisjumatsabtuTambah' or . = 'Registrasi Tenaga MedisNamaNomor LisensiEmailPasswordJam MulaiUpload FotoTanggal lahirStatus PerkawinanBelum MenikahMenikahSpesialisUmum 2Spesialis penyakit dalamSpesialis penyakit dalamNo TeleponJam SelesaiJadwalmingguseninselasarabukamisjumatsabtuTambah')]</value>
      <webElementGuid>9ac50a48-e402-4f26-9dc6-9a90184d7e15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
