<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_11234509878 Adityo Rahman 6 tahunLaki -_3ac129</name>
   <tag></tag>
   <elementGuidId>c9f72485-a6c8-40d0-9bf5-84f25661b7ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/table/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.border._PaddingTopBottom_1knu3_17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ac1938d-5365-482f-a37e-673ac0e7655d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border _PaddingTopBottom_1knu3_17</value>
      <webElementGuid>0f93bac3-f28f-4b11-8afc-2f58b4539ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11234509878 Adityo Rahman 6 tahunLaki - Laki 0812121213 2022-12-14 •••Edit DataHapus DataRiwayat PasienTambah Rawat Jalan</value>
      <webElementGuid>2ef28822-0200-4e3e-8d7f-ec8e2d8ce89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container border&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-borderless text-center poppins-font&quot;]/div[2]/div[@class=&quot;border _PaddingTopBottom_1knu3_17&quot;]</value>
      <webElementGuid>979f36c5-b0f1-4b83-9e56-76e542bdbf68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/div/table/div[2]/div</value>
      <webElementGuid>c09e681d-e651-4120-8a28-e40ad9c1b203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Daftar'])[1]/following::div[2]</value>
      <webElementGuid>ae53aab4-1d00-465d-a339-7601bcc3f44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.Hp'])[1]/following::div[2]</value>
      <webElementGuid>064ab55a-7671-437b-91d9-eee69ff89071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table/div[2]/div</value>
      <webElementGuid>4c42b18b-86d4-433a-9bd4-99c0eb5364b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '11234509878 Adityo Rahman 6 tahunLaki - Laki 0812121213 2022-12-14 •••Edit DataHapus DataRiwayat PasienTambah Rawat Jalan' or . = '11234509878 Adityo Rahman 6 tahunLaki - Laki 0812121213 2022-12-14 •••Edit DataHapus DataRiwayat PasienTambah Rawat Jalan')]</value>
      <webElementGuid>63db5c76-9858-4e89-a193-87e2d2c93e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
