<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_ABOUT</name>
   <tag></tag>
   <elementGuidId>412a1411-7339-4727-86bc-667d5f140ad1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div/div/ul/li[2]/a/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>82667d72-6c79-4114-895d-1967c8f2dce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABOUT</value>
      <webElementGuid>48c051a1-d7cb-4e46-8f10-62f1432c50d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;_bgHeader_16ww9_1&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start&quot;]/ul[@class=&quot;nav col-12 col-lg-auto justify-content-center text-small&quot;]/li[2]/a[@class=&quot;nav-link mt-2 mx-4&quot;]/h2[1]</value>
      <webElementGuid>3d70f45a-1e2b-4644-9cd7-b12c13ca2ea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/div/ul/li[2]/a/h2</value>
      <webElementGuid>36bdcc14-186d-4e1b-90e5-ff6c1abc394f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::h2[1]</value>
      <webElementGuid>4146d899-3534-4a8b-bfe8-195856f637fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SERVICES'])[1]/preceding::h2[1]</value>
      <webElementGuid>a207c948-52a2-42b9-bf2e-c5bd595fbb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOWNLOAD'])[1]/preceding::h2[2]</value>
      <webElementGuid>88056037-6d6f-48a0-a65f-7279359adbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ABOUT']/parent::*</value>
      <webElementGuid>1fbfcd19-5c2b-492c-b06f-93ec5752dec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/h2</value>
      <webElementGuid>e37667e9-aa48-4f3c-a9dc-1d361a6ad83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'ABOUT' or . = 'ABOUT')]</value>
      <webElementGuid>1a6247c9-9e71-4457-9fed-f514fc48f14c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
