<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Login</name>
   <tag></tag>
   <elementGuidId>dc68c2d2-775a-4df4-b5b5-84ccb4711c7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div/div/ul/li[5]/a/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.text-sm-start.py-2.px-3.mx-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5b5fc293-a653-4520-9ada-e1d8d01062e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm-start py-2 px-3 mx-4</value>
      <webElementGuid>dd2e949a-9968-456c-9ae3-6d0a07db7f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>9eeb7a08-92cf-4587-86a4-eb167fa3cb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;_bgHeader_16ww9_1&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start&quot;]/ul[@class=&quot;nav col-12 col-lg-auto justify-content-center text-small&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/div[1]/h2[@class=&quot;text-sm-start py-2 px-3 mx-4&quot;]</value>
      <webElementGuid>e7bc8efa-91ae-4919-a03b-cb9369eca7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f4ceb479-5567-45dc-9b29-9fdf7c610e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm-start py-2 px-3 mx-4</value>
      <webElementGuid>c8ac8d9b-5e96-4ef0-aa07-ca0c5b6bfbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>64996ff7-13a2-4585-9998-078c2d8ecd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;_bgHeader_16ww9_1&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start&quot;]/ul[@class=&quot;nav col-12 col-lg-auto justify-content-center text-small&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/div[1]/h2[@class=&quot;text-sm-start py-2 px-3 mx-4&quot;]</value>
      <webElementGuid>723ecf92-e561-4042-90c9-dd21d95bfc5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/div/ul/li[5]/a/div/h2</value>
      <webElementGuid>fe05facf-9d26-4280-aaac-b5e38916e552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOWNLOAD'])[1]/following::h2[1]</value>
      <webElementGuid>85da82f0-d2d6-42f0-9962-da9852928b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SERVICES'])[1]/following::h2[2]</value>
      <webElementGuid>d7d4d465-8da6-49d9-be21-4504f5495520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinic'])[2]/preceding::h2[1]</value>
      <webElementGuid>226e2ab4-8b25-4a3b-a7ca-626a9bf116c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>97af2a09-a122-4ec1-bc21-e46b0325d159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/h2</value>
      <webElementGuid>ae5d5d21-484d-49a2-a83b-4e47fccc3429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>00c68ffc-d5f4-4c21-a705-924553fc8853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
