<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Account</name>
   <tag></tag>
   <elementGuidId>84b8a71c-5d8b-41b5-8826-314a4ca86917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/a[4]/div/button/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>6e1a7817-0e2f-45e9-bb79-58594c8a2044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>d78aead2-1167-4168-8277-5c90f73e5ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>e752ac76-07d2-40a6-85bd-a3211935fd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/a[@class=&quot;text-decoration-none link mb-3&quot;]/div[@class=&quot;link&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 collapsed&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>58281d3e-67c3-4e72-9b3e-60a3ee14ec8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/a[4]/div/button/h5</value>
      <webElementGuid>6e60fa61-f05a-4384-aad9-8f6fcb46e706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/following::h5[1]</value>
      <webElementGuid>d63d30bb-3dac-4c96-8578-784dc5517fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctors'])[1]/following::h5[2]</value>
      <webElementGuid>ee7c7b99-395b-44df-912a-26dfd757ead3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::h5[1]</value>
      <webElementGuid>5e7f56b9-03f1-4516-b98d-322e5ea650d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::h5[2]</value>
      <webElementGuid>18a47cc6-b899-48c1-9dea-cc79807c9a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account']/parent::*</value>
      <webElementGuid>d654ccf4-c0c4-4edb-84ec-49ce99033f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/button/h5</value>
      <webElementGuid>fb95fcdb-afe2-4361-9613-7286846c5d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>1b879f12-b97a-4d74-b46f-57c9c87dd45b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
