<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Patient</name>
   <tag></tag>
   <elementGuidId>e95410da-a986-4257-a46a-ba4ee10a491e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/span/div/div/button/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-toggle.d-inline-flex.border-0.poppins-font > h5.d-none.d-md-block.ms-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>0e21fc04-e0c1-451d-9ba6-ff44e2c18e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>b51b48c5-effa-4019-a658-a4d891df2d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>8aa8a71e-46f3-43d3-9082-1ecc1af75645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>2d52e17c-14d6-4e71-98aa-ebf2425fbcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>eb1d7693-1022-4b42-8625-226c97405054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>e9d5d39b-35ff-437b-991f-620e9b044756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>29ef9247-ea96-4360-b303-758dfae89bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font collapsed&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>f3e8e94d-2c15-4c34-a78a-a0323833639a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>cf11c7af-4e8b-400b-9b0a-f7bdf8905be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>d978ade3-7182-447a-8395-a6d0495b8c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>43bda29e-21ac-46da-adcc-1b3199ea1ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>26eff9df-c0cf-4edd-a836-d72cb2ec11a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>39ef1bcd-052f-4fba-954b-fbb0e8f31784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>018203c0-e196-43af-99ba-9f7211d0e0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>9199a3fe-fef5-494f-9b4f-391b5883e93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>87b13cf9-36d6-4c50-9795-d27b67f641f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>dc1d2196-2b2d-4cf0-9657-47dbb8fe6902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>aed687ef-7cbc-4ffc-b765-52760ac7f87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>67c2ce8b-66c0-429a-b10c-430c546f65e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>24d31298-13bf-439e-8b91-3e681567810e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>9046691a-1bb1-4d6d-a0df-a76fd1bf25d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>62497af7-957c-485f-b849-01de06d44170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>416db72a-3bed-4dc7-8f57-cc52d81a9d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>d1e35389-f333-4340-8c11-f0b74b45ce78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>e3739480-f794-4055-bbe6-ed3198f4cb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>b194728c-3567-4f4c-b2da-198b51d70d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>e95362b6-1f5b-492d-8776-b2204a0d7de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>f5279f70-fbe2-4f80-a9b9-5dc286314721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>4f24b593-301f-4dd5-acf4-c0b4ec238a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>dafd6e85-738f-4e44-b879-49a071a640cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>b9bd2a1c-9e17-4a47-99c6-a26998d8fb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>84028c07-ad4a-4f45-99d5-773304d5bbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>72282d42-e7ba-4375-8697-7530d5c05e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>989da961-ec4f-47b1-86ae-24843aa0ce8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>f7ca7794-772d-46fb-9796-048ec07d1d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>ac6bea6d-66e6-4735-959c-1b279399587f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>c5743487-d952-4b57-bc63-0943fabc31ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>83e96299-ade4-4c4c-970d-da7c71d361df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>91ae6e12-d608-4778-b790-07800a6206c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>487b2fc5-6578-4ef4-8fff-f1692b13f31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>1e33c30c-839d-40d8-a30f-1dcfedcd6b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>cb355f4b-8193-40fb-9341-3f7856aaf8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>a37e58d5-97e9-42c7-95a1-a3d31ac0036e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>f77d3860-1f48-4c51-bf9d-ac748a72ee63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>4bc4a9ef-6a67-426d-a3d2-44e9ebb1ebcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block ms-3</value>
      <webElementGuid>388d83d4-193c-4704-8ea2-6aa33e41a3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>0d6ff81a-c1c5-4d4f-9fc7-a5bac6c5a075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shadow sidebar sticky-top col-2&quot;]/div[2]/span[@class=&quot;text-decoration-none link mb-3&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/button[@class=&quot;btn btn-toggle d-inline-flex border-0 poppins-font&quot;]/h5[@class=&quot;d-none d-md-block ms-3&quot;]</value>
      <webElementGuid>8d4bb15f-a767-48b4-a802-02447b5e5808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/span/div/div/button/h5</value>
      <webElementGuid>c354dcf8-b4bf-4061-967a-fb0690e7d89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::h5[1]</value>
      <webElementGuid>61df971f-57f0-4a46-96e9-e9d71f8cb7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinic'])[2]/following::h5[2]</value>
      <webElementGuid>0b0fd3f0-16f5-4a27-b583-d43644422dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctors'])[1]/preceding::h5[1]</value>
      <webElementGuid>69ca88d4-2aed-4105-a325-f4c460e87d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/preceding::h5[2]</value>
      <webElementGuid>223a7094-30be-46ec-a94b-8c4f30acc7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patient']/parent::*</value>
      <webElementGuid>58580066-acb2-45a8-bf13-d190d3b088bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button/h5</value>
      <webElementGuid>619c291a-4fc0-43f4-bccc-5d8300b0efef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Patient' or . = 'Patient')]</value>
      <webElementGuid>552d4b7d-5b60-4347-87ba-b727cc06a721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
