<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>85625785-b266-49e0-b863-c74d8866e669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[3]/div/div[2]/ul/li[8]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>89b159bb-b5fc-4587-8593-a73d95f06361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Right.9141d5df.svg</value>
      <webElementGuid>938692f8-fabc-4731-8765-2fbca87cff80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad72b757-10ab-43d3-9664-f1a5e5566d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;border mt-4 container text-center border-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 ms-auto d-flex justify-content-center&quot;]/ul[@class=&quot;pageNumbers&quot;]/li[8]/button[1]/img[1]</value>
      <webElementGuid>e180bce3-af07-46a5-828e-208fccbbac5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>40fe59e3-c4b1-4ea6-b28e-b644c6211366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Right.9141d5df.svg</value>
      <webElementGuid>079844b2-2d3c-492b-9c43-2a97abb338b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>34c9f647-52a6-4e0a-b17e-d60d6daff1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;border mt-4 container text-center border-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 ms-auto d-flex justify-content-center&quot;]/ul[@class=&quot;pageNumbers&quot;]/li[8]/button[1]/img[1]</value>
      <webElementGuid>0b8c81ec-f805-4c99-89d4-2babdd2f61f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[3]/div/div[2]/ul/li[8]/button/img</value>
      <webElementGuid>ee305396-94ca-4c7a-84b6-8e4ce12c0f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='img'])[2]</value>
      <webElementGuid>44c2f5a9-b9cf-478b-b51a-573f7f0d9cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/button/img</value>
      <webElementGuid>915b5173-9371-4f58-92f1-c3a0b6203449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Right.9141d5df.svg' and @alt = 'img']</value>
      <webElementGuid>2cde56ef-02c0-4761-bdeb-708b0f6b77de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
