<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_nik</name>
   <tag></tag>
   <elementGuidId>a00c88f0-f66f-4811-b217-f64fdc2201a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nik']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nik&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2216708a-546f-48fe-93ab-b25898fa93ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>d521b98e-bc08-4224-95ed-4081a8f2e32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7d1ca38-0dd6-4cfa-870a-9ba89614798b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3e8b99a1-7a9d-492b-8deb-915636f3afd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234567</value>
      <webElementGuid>710712de-05fe-4dd7-99dc-3fac7828b72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;[object Object]&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;show-grid modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-6&quot;]/div[@class=&quot;mb-2&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>335e03be-b7ff-42f0-9367-738a1b7d9b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe231520-b01d-42fb-b2e6-5e410c40b047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>ccbee2b9-9d1b-4f1a-a7a7-01248a8e2919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2564044d-70f4-46dc-b4bd-5f4293169f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9cb4b528-1350-4d8a-b6e5-4abbb18e4032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234509879</value>
      <webElementGuid>f035e48e-6cbf-4cf0-8e44-562c75e3f012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;[object Object]&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;show-grid modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-6&quot;]/div[@class=&quot;mb-2&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4ad3f2c0-51cf-4a59-aef0-8f944398e94e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nik']</value>
      <webElementGuid>6f2ce676-536f-4a2a-a7d9-1e40e51caecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='[object Object]']/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>80c163ae-d54a-4363-bdee-87458b538c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>1f9a7e8d-62e1-4896-bbf7-73c5ba954e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nik' and @type = 'text']</value>
      <webElementGuid>43625a1e-9b2e-4d79-8083-3d0836092813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
