<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data Pasien_border border-0 ps-5 shad_eae0bb</name>
   <tag></tag>
   <elementGuidId>fcb0a013-717a-4468-822b-496a88033e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.border.border-0.ps-5.shadow.bg-light.text-dark.pe-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1921873c-2836-4e54-a209-edf0d2b88658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4c8395c8-25bb-431f-b878-70a5eb4e6877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>72c4a12f-aed2-4c8d-8c20-0edb64e60f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-0 ps-5 shadow bg-light text-dark pe-4</value>
      <webElementGuid>e7d429b7-9573-4115-bbf9-35377e52c111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container text-center&quot;]/div[@class=&quot;row row-cols-2 row-cols-lg-4 g-2 g-lg-4 d-flex position-relative&quot;]/div[@class=&quot;ms-auto d-none d-md-flex&quot;]/div[1]/input[@class=&quot;border border-0 ps-5 shadow bg-light text-dark pe-4&quot;]</value>
      <webElementGuid>ce8a60d2-d111-424d-92b9-3449199eb0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d177a7f4-dd8c-4941-9a68-5294258dd857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>2561ef5d-8783-4ff9-b0d9-b74e9afe9df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>69fbc734-e4d2-438d-9faf-0c73f0365099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-0 ps-5 shadow bg-light text-dark pe-4</value>
      <webElementGuid>77a7f6fa-c615-499e-a386-4fb7713a769c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container text-center&quot;]/div[@class=&quot;row row-cols-2 row-cols-lg-4 g-2 g-lg-4 d-flex position-relative&quot;]/div[@class=&quot;ms-auto d-none d-md-flex&quot;]/div[1]/input[@class=&quot;border border-0 ps-5 shadow bg-light text-dark pe-4&quot;]</value>
      <webElementGuid>9d7148c2-ee7a-428a-b16e-6b08a1941522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>5bca9855-f29f-469c-b77c-62b66da7d17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>4a891d58-f8b7-4264-a7af-c9d9ea2ac11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f88a300f-b2d1-410e-acfe-5d0e87367b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Cari']</value>
      <webElementGuid>662d5d89-33f7-412d-b035-864f22d55a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
