<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Data Pasien</name>
   <tag></tag>
   <elementGuidId>b21a368c-261f-4783-b89a-5bbbf8a70db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-collapse']/ul/li/a/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.poppins-font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>008ff049-d031-4f95-b7fd-e35d8241b158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>21fb2ae1-1f28-476c-a2c1-5b8c0ef67b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>5b7f0f69-1094-482a-a0ef-57bae5b95a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>f005e62e-b194-49c7-985c-11c304efac39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>117b0f3f-135b-4840-b2f9-5201a6697a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>1716db9a-a2be-4a76-ba5d-fd97eb8956c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>1cafb9ad-e3f9-4737-b879-9a5a57623733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>0bca2c1c-8a4b-45ae-8ca7-1dfd0dbbe3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b74c6dbf-06aa-4135-8b9c-540ad23bedac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>b071dd54-f6be-4b53-b71d-e2aade233516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>3f6b4fbb-8660-46c6-9870-12eff2f3fe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>efd44b95-d034-4453-b74b-5b84177f6a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e489152d-618c-4dad-9f11-d31dc603b5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>9b64a94c-63be-4dab-a462-26c7112e7f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>12483ab9-e847-45ce-b9ab-7f1226f6dd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>d13ea94e-00d7-407e-bb3a-613167988fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>53baf4e3-0c12-4244-85be-c7c1d7c20edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>9dce776e-924d-49ee-aee9-3368b1788252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>de11071c-bc7a-4bbe-bd99-c731c9940e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>6666a1ab-ba6e-466b-8971-4bde3eb5544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1e104eec-7ae9-4c6e-b037-ba310692200a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>3ad70c69-0342-4ea9-a1b2-51c212dfb324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>e41b85fa-b56c-4bba-9cd9-235006f6efdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>8734082b-64a4-4c28-b1f4-ed58fedc8d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6a4d62cd-f11d-45f6-bad5-3032e899ebd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>5fa6d601-aef4-4819-9d4c-095a66954c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>e7be5466-ee58-4606-b2c3-1b5cde253787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>dbbebef6-640f-4919-8fcb-e54ebeb033d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>86ba6785-189b-4c05-9ea0-16f357b77b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>91f5ec60-f304-4a61-acd8-474077fc4995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>18b6a470-3b7c-4e53-bd40-430816bf7c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>8de545bb-b876-4e2e-a5a4-ce6ab36eb0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>013edb72-c3fc-4c4c-9d95-a3dc03bfaa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>cfa00e67-4551-45cc-bb2e-7c96e1ebbb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>5ade4827-1ae6-4921-9b29-acd8a76fe7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>4d7955b1-183f-48b4-bc04-e62ab218d8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4640ac7c-d62d-49ed-b10e-aa581c9312f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>f5f435df-8862-4bdf-a33b-3803c062b747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>565be58d-d805-4d64-b388-a78023f48107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>8190e311-5652-4bc7-83e5-901aa2d33053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>956af02a-a046-4b5f-95fd-6be59f2f54ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>cddba10f-f50a-4331-bee9-79ebc2dfd277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>dcf8108c-163a-4ac1-a448-fe19dc13a4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>ec3b1aea-1bd0-4e71-a896-c0138cea0e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>540f4b53-ec48-4910-b23c-c57e0dc51572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>d593222f-e091-452c-b98e-adfd29f4fb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>7ac44148-ad95-4ea3-bd4b-f0fbe3a82435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>5d5fa886-f9fe-4f72-92b3-3ee0b5212da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2bf610b4-535b-45fb-acc4-30e2ebc87b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>24398c29-2208-4ac7-8e97-bc17c3257fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>f8c5b434-ef7a-4a4c-bb83-e41bbae0d72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>c170499e-6817-48eb-93ae-83bfa10d9cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d21f18c1-5100-4877-98f7-9536826e5b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>073f7cf4-253d-4bd8-a52e-c7fbf0def81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>01b09924-9a06-4bff-b22e-6dd4e33bd17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>1938323e-1da5-478b-a536-559f0aadc5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f5671593-8954-4cc5-8c3c-354d543ea518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>9ed8080a-c83e-4029-9d94-5a44e1947b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>83d03abb-bba5-4997-886c-b1727979a803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>6116ba6c-a9c8-4964-84b1-e0e393df0304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4ea049ea-2c68-4e3d-a9b3-696a542f5ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>1bc0fdac-bc5b-438a-ba41-268cbe4b9ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>e436e57b-8f9f-4164-9097-ce0669d8b0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>b60782ce-9ff7-4fa1-a8d0-143ba68d4ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e7c8c11e-854e-4952-bd41-ff02b11e40fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>cb9b35d3-c4d8-4c0a-9eeb-1bde5e721f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>2ada7fc2-e2ff-4895-a75c-d7c585c07f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>6c62f224-f9ad-4a32-b0b3-7ad6249e9b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1529ca2c-cfb1-4eb0-9cff-7e8cdef30b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>a334890a-7788-4158-b5c2-c631fab5320e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>86ec67fe-ea77-41d6-bfe2-26e16285dc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>9408f691-485a-4aa2-8e89-c7546065be14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9c3acf8c-5244-40b5-8c21-4133df5b7530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppins-font</value>
      <webElementGuid>294df876-5c3f-4267-a94e-0dfac29bc00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Pasien</value>
      <webElementGuid>61561bd8-4059-490b-ac6c-b1b66a1bbecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small&quot;]/li[@class=&quot;link&quot;]/a[@class=&quot;link-dark d-inline-flex text-decoration-none rounded&quot;]/p[@class=&quot;poppins-font&quot;]</value>
      <webElementGuid>71e98d02-7803-4ffc-8efa-680e024b9667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-collapse']/ul/li/a/p</value>
      <webElementGuid>e5f1469d-6c3d-4de8-aef0-38296616a501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient'])[1]/following::p[1]</value>
      <webElementGuid>f2122a4e-03b0-433b-8a50-4b537cc80c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::p[1]</value>
      <webElementGuid>f405ad24-4a4e-40d5-b5a3-859fd0024c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctors'])[1]/preceding::p[2]</value>
      <webElementGuid>5d36bcd7-ad8f-4e8a-af13-d3b5440b611b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/preceding::p[2]</value>
      <webElementGuid>920e81d8-a91b-442f-8024-c231b555c673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Data Pasien']/parent::*</value>
      <webElementGuid>a5b76a1d-ffbd-4809-9612-6e89cd522275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>5e4f2f3f-51ad-4bc1-8068-c3445d89a437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Data Pasien' or . = 'Data Pasien')]</value>
      <webElementGuid>0f14a3a7-6971-400d-9cfc-1fab58b97fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
